### PR TITLE
Fix peer dependency for react 17.0.x

### PR DESCRIPTION
**Pull request by mariuz**
Related tweet 

https://twitter.com/wesbos/status/1359173446740172810

Fixes Could not resolve dependency:
peer react@"^16.4.2" from redux-form@8.3.7

https://github.com/redux-form/redux-form/issues/4721

and 

https://github.com/redux-form/redux-form/issues/4710

### CODE REVIEW

**Comment by sanex3339** [comment]
Please merge this.

**Comment by sanex3339** [comment]
@erikras

**Comment by sanex3339** [comment]
@erikras please merge this.

**Comment by sanex3339** [comment]
Also if this project won't get any updates with the react 17 and upcoming react 18 we have to fork this project.
In our project about 30-40 forms created with redux-form and many components within the page are interacting with the forms via actions (and affected by form values), so we have a very complicated business logic with interactions and cannot just migrate these forms to final-form (about 60% of forms can be migrated, 40% of most complicated forms can't), so we need this project to be updated to work with the latest react/redux and so (we have no bugs so we need only support to work with the latest dependencies)

**Comment by sanex3339** [comment]
@erikras please merge this and release a new version.
If this project needs another maintainer - please select it. We highly depend on this project and we don't want to create a fork just because of react support

**Comment by sanex3339** [comment]
Also what we have to get this merged?

**Comment by erikras** [comment]
Released in [`v8.3.8`](https://github.com/redux-form/redux-form/releases/tag/v8.3.8).

**Pull request merged**
