### PR TITLE
Remove UNSAFE_componentWillMount and fix initialValues not passed to validation

### PR DESCRIPTION
**Pull request by sanex3339**
Remove UNSAFE_componentWillMount and fix initialValues not passed to validation.

Issues: https://github.com/redux-form/redux-form/issues/4628, https://github.com/redux-form/redux-form/issues/4642
Partially ported from https://github.com/shanshanzhu/redux-form/commit/d59ea8e0ff374f45c20f463b36f7101985b3eba2

Updated React development version to 17.0.2

### CODE REVIEW

**Comment by sanex3339** [comment]
@erikras hi, as we discussed, please check this.
Still 4 `UNSAFE` lifecycle methods are left, i'm not sure how to rewrite it, tests are failing.

**Comment by Cetlan** [comment]
Maybe outside the scope of this fix, but to be (perhaps a bit too) blunt, the problem here is https://github.com/redux-form/redux-form/pull/4020 It *might* have fixed a bug with the wrong values being passed in under one particular set of conditions - but completely broke the behaviour of initial setup, where previously the `values` prop was set up to be the intialValues when first set up, and now it's set up to be an empty object because the initialization logic was inverted without account for the reason it was written that was in the first place.

So, validation not getting `initialValues` is just the symptom that everyone has started to notice about that change, but anything that relies on `values` could be broken. I won't pretend to know enough of the redux-form code to know if your fix is general enough to account for that, but as I spent *days* trying to understand why upgrading redux-form broke the application I'm working with, I figured I'd make note of the more general possible problem since you're working on it.

**Comment by sanex3339** [comment]
@shanshanzhu please check this too, because it based in your changes

**Comment by shanshanzhu** [comment]
@sanex3339 LGTM

**Comment by dominikduda** [comment]
Is there any ETA of when will this be released?

**Comment by jaketrimble** [comment]
Checking in on an ETA for release. Thanks!

**Comment by vladkosinov** [comment]
@erikras @iamandrewluca is the a chance this PR or https://github.com/redux-form/redux-form/pull/4728 will be merged?

**Comment by sbaechler** [comment]
This would also fix parts of #4373 and #3954

**Comment by kimyu92** [comment]
@erikras May you review this PR to enable React 17 support to prevent it falling behind too far especially React 18 has been out for a few months? 🙏

**Comment by gaievskyi** [comment]
@erikras UP 🙏

**Comment by sanex3339** [comment]
👍

**Comment by haradakunihiko** [comment]
@erikras May I ask when this will be released? I am eagerly awaiting this fix.

**Comment by erikras** [comment]
Published in [`v8.3.10`](https://github.com/redux-form/redux-form/releases/tag/v8.3.10).

**Pull request merged**
