### PR TITLE
make immutable an optional dep

### PR DESCRIPTION
**Pull request by esetnik**
https://yarnpkg.com/configuration/manifest#peerDependenciesMeta

### CODE REVIEW

**Comment by iamandrewluca** [comment]
@esetnik nice. Does `npm` recognize this, or only yarn?

**Comment by iamandrewluca** [comment]
Ok it seems it does recognize it
https://github.com/npm/cli/commit/a12341088820c0e7ef6c1c0db3c657f0c2b3943e

**Comment by esetnik** [comment]
@iamandrewluca any idea when the next release will be?

**Comment by iamandrewluca** [comment]
I'll contact Erik, I don't have permissions on npm.

**Comment by renatoagds** [comment]
@iamandrewluca  I could help on release it, will prepare a release for next week ;)

**Comment by renatoagds** [comment]
Published in [`v8.3.2`](https://github.com/redux-form/redux-form/releases/tag/v8.3.2).

**Pull request merged**
